// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/durable.proto

package durable

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Handler       string                 `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Args          []byte                 `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	PartitionKey  string                 `protobuf:"bytes,5,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	Sequence      int64                  `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_durable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_durable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_durable_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *Command) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *Command) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Command) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *Command) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type JournalEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepNumber    int32                  `protobuf:"varint,1,opt,name=step_number,json=stepNumber,proto3" json:"step_number,omitempty"`
	StepType      string                 `protobuf:"bytes,2,opt,name=step_type,json=stepType,proto3" json:"step_type,omitempty"`
	Request       []byte                 `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Response      []byte                 `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	mi := &file_proto_durable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_durable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_proto_durable_proto_rawDescGZIP(), []int{1}
}

func (x *JournalEntry) GetStepNumber() int32 {
	if x != nil {
		return x.StepNumber
	}
	return 0
}

func (x *JournalEntry) GetStepType() string {
	if x != nil {
		return x.StepType
	}
	return ""
}

func (x *JournalEntry) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *JournalEntry) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *JournalEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AwakeableState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AwakeableId   string                 `protobuf:"bytes,1,opt,name=awakeable_id,json=awakeableId,proto3" json:"awakeable_id,omitempty"`    // Unique ID for this awakeable
	InvocationId  string                 `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"` // Workflow invocation waiting for this
	Resolved      bool                   `protobuf:"varint,3,opt,name=resolved,proto3" json:"resolved,omitempty"`                            // Whether awakeable has been resolved
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`                                 // Result data (if resolved)
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                   // Error message (if rejected)
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`         // Timestamp when created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwakeableState) Reset() {
	*x = AwakeableState{}
	mi := &file_proto_durable_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwakeableState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwakeableState) ProtoMessage() {}

func (x *AwakeableState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_durable_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwakeableState.ProtoReflect.Descriptor instead.
func (*AwakeableState) Descriptor() ([]byte, []int) {
	return file_proto_durable_proto_rawDescGZIP(), []int{2}
}

func (x *AwakeableState) GetAwakeableId() string {
	if x != nil {
		return x.AwakeableId
	}
	return ""
}

func (x *AwakeableState) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *AwakeableState) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

func (x *AwakeableState) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AwakeableState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AwakeableState) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ExecutionState struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	InvocationId    string                     `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Handler         string                     `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
	Journal         []*JournalEntry            `protobuf:"bytes,3,rep,name=journal,proto3" json:"journal,omitempty"`
	CurrentState    []byte                     `protobuf:"bytes,4,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"` // Deprecated: use workflow_state instead
	Status          string                     `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep     int32                      `protobuf:"varint,6,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`                                                                                // Current step number being executed (-1 if not started)
	CurrentStepType string                     `protobuf:"bytes,7,opt,name=current_step_type,json=currentStepType,proto3" json:"current_step_type,omitempty"`                                                                   // Type of current step (e.g., "HelloService.SayHello")
	WorkflowState   map[string][]byte          `protobuf:"bytes,8,rep,name=workflow_state,json=workflowState,proto3" json:"workflow_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Workflow-scoped state (ctx.Get/Set)
	Awakeables      map[string]*AwakeableState `protobuf:"bytes,9,rep,name=awakeables,proto3" json:"awakeables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`                            // Awakeables waiting for external completion
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionState) Reset() {
	*x = ExecutionState{}
	mi := &file_proto_durable_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionState) ProtoMessage() {}

func (x *ExecutionState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_durable_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionState.ProtoReflect.Descriptor instead.
func (*ExecutionState) Descriptor() ([]byte, []int) {
	return file_proto_durable_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionState) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *ExecutionState) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *ExecutionState) GetJournal() []*JournalEntry {
	if x != nil {
		return x.Journal
	}
	return nil
}

func (x *ExecutionState) GetCurrentState() []byte {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *ExecutionState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionState) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *ExecutionState) GetCurrentStepType() string {
	if x != nil {
		return x.CurrentStepType
	}
	return ""
}

func (x *ExecutionState) GetWorkflowState() map[string][]byte {
	if x != nil {
		return x.WorkflowState
	}
	return nil
}

func (x *ExecutionState) GetAwakeables() map[string]*AwakeableState {
	if x != nil {
		return x.Awakeables
	}
	return nil
}

var File_proto_durable_proto protoreflect.FileDescriptor

const file_proto_durable_proto_rawDesc = "" +
	"\n" +
	"\x13proto/durable.proto\x12\adurable\"\xb7\x01\n" +
	"\aCommand\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x18\n" +
	"\ahandler\x18\x02 \x01(\tR\ahandler\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x12\n" +
	"\x04args\x18\x04 \x01(\fR\x04args\x12#\n" +
	"\rpartition_key\x18\x05 \x01(\tR\fpartitionKey\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x03R\bsequence\"\x98\x01\n" +
	"\fJournalEntry\x12\x1f\n" +
	"\vstep_number\x18\x01 \x01(\x05R\n" +
	"stepNumber\x12\x1b\n" +
	"\tstep_type\x18\x02 \x01(\tR\bstepType\x12\x18\n" +
	"\arequest\x18\x03 \x01(\fR\arequest\x12\x1a\n" +
	"\bresponse\x18\x04 \x01(\fR\bresponse\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xc1\x01\n" +
	"\x0eAwakeableState\x12!\n" +
	"\fawakeable_id\x18\x01 \x01(\tR\vawakeableId\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\x12\x1a\n" +
	"\bresolved\x18\x03 \x01(\bR\bresolved\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\xc2\x04\n" +
	"\x0eExecutionState\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12\x18\n" +
	"\ahandler\x18\x02 \x01(\tR\ahandler\x12/\n" +
	"\ajournal\x18\x03 \x03(\v2\x15.durable.JournalEntryR\ajournal\x12#\n" +
	"\rcurrent_state\x18\x04 \x01(\fR\fcurrentState\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x06 \x01(\x05R\vcurrentStep\x12*\n" +
	"\x11current_step_type\x18\a \x01(\tR\x0fcurrentStepType\x12Q\n" +
	"\x0eworkflow_state\x18\b \x03(\v2*.durable.ExecutionState.WorkflowStateEntryR\rworkflowState\x12G\n" +
	"\n" +
	"awakeables\x18\t \x03(\v2'.durable.ExecutionState.AwakeablesEntryR\n" +
	"awakeables\x1a@\n" +
	"\x12WorkflowStateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aV\n" +
	"\x0fAwakeablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.durable.AwakeableStateR\x05value:\x028\x01B8Z6github.com/sanjaymijar/my-durable-execution/pb/durableb\x06proto3"

var (
	file_proto_durable_proto_rawDescOnce sync.Once
	file_proto_durable_proto_rawDescData []byte
)

func file_proto_durable_proto_rawDescGZIP() []byte {
	file_proto_durable_proto_rawDescOnce.Do(func() {
		file_proto_durable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_durable_proto_rawDesc), len(file_proto_durable_proto_rawDesc)))
	})
	return file_proto_durable_proto_rawDescData
}

var file_proto_durable_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_durable_proto_goTypes = []any{
	(*Command)(nil),        // 0: durable.Command
	(*JournalEntry)(nil),   // 1: durable.JournalEntry
	(*AwakeableState)(nil), // 2: durable.AwakeableState
	(*ExecutionState)(nil), // 3: durable.ExecutionState
	nil,                    // 4: durable.ExecutionState.WorkflowStateEntry
	nil,                    // 5: durable.ExecutionState.AwakeablesEntry
}
var file_proto_durable_proto_depIdxs = []int32{
	1, // 0: durable.ExecutionState.journal:type_name -> durable.JournalEntry
	4, // 1: durable.ExecutionState.workflow_state:type_name -> durable.ExecutionState.WorkflowStateEntry
	5, // 2: durable.ExecutionState.awakeables:type_name -> durable.ExecutionState.AwakeablesEntry
	2, // 3: durable.ExecutionState.AwakeablesEntry.value:type_name -> durable.AwakeableState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_durable_proto_init() }
func file_proto_durable_proto_init() {
	if File_proto_durable_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_durable_proto_rawDesc), len(file_proto_durable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_durable_proto_goTypes,
		DependencyIndexes: file_proto_durable_proto_depIdxs,
		MessageInfos:      file_proto_durable_proto_msgTypes,
	}.Build()
	File_proto_durable_proto = out.File
	file_proto_durable_proto_goTypes = nil
	file_proto_durable_proto_depIdxs = nil
}
